// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_Al0Yxs128453lG1vzQCmybc_VXE9gc',
    appId: '1:537587848500:web:1e3715303148094bf10161',
    messagingSenderId: '537587848500',
    projectId: 'findit-wec-2026',
    authDomain: 'findit-wec-2026.firebaseapp.com',
    storageBucket: 'findit-wec-2026.firebasestorage.app',
    measurementId: 'G-QQSXF178LL',
    databaseURL: 'https://findit-wec-2026-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBe-OP7KiPt7KOgQ5GSDXDju35S1EixEA',
    appId: '1:537587848500:android:c6a82c475375e20df10161',
    messagingSenderId: '537587848500',
    projectId: 'findit-wec-2026',
    storageBucket: 'findit-wec-2026.firebasestorage.app',
    databaseURL: 'https://findit-wec-2026-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkirgKWjelzsPiEcKtXpdKbh5A09sZhqE',
    appId: '1:537587848500:ios:51274dcabefd89c8f10161',
    messagingSenderId: '537587848500',
    projectId: 'findit-wec-2026',
    storageBucket: 'findit-wec-2026.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkirgKWjelzsPiEcKtXpdKbh5A09sZhqE',
    appId: '1:537587848500:ios:51274dcabefd89c8f10161',
    messagingSenderId: '537587848500',
    projectId: 'findit-wec-2026',
    storageBucket: 'findit-wec-2026.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA_Al0Yxs128453lG1vzQCmybc_VXE9gc',
    appId: '1:537587848500:web:ca30d1188d2076eef10161',
    messagingSenderId: '537587848500',
    projectId: 'findit-wec-2026',
    authDomain: 'findit-wec-2026.firebaseapp.com',
    storageBucket: 'findit-wec-2026.firebasestorage.app',
    measurementId: 'G-JLD3ENGZG5',
  );
}
